// Explicit icon registry so only the icons we actually use are bundled
// (avoids `import * as Icons` which defeats tree-shaking).
import {
  Sparkles,
  Flame,
  Scissors,
  Languages,
  Compass,
  Hotel,
  Cpu,
  GraduationCap,
  Stethoscope,
  Mic,
  Briefcase,
  Library,
  CircuitBoard,
  Flower2,
  Network,
  Clapperboard,
  Cog,
  Code2,
  FileCode,
  HeartPulse,
  Hammer,
  BookOpenCheck,
  Award,
  Users,
  Wrench,
  CalendarClock,
  Wallet,
  BadgeCheck,
  BookOpen,
  TrendingUp,
  ThumbsUp,
  Trophy,
  HeartHandshake,
  Circle,
} from 'lucide-react';

const registry = {
  Sparkles,
  Flame,
  Scissors,
  Languages,
  Compass,
  Hotel,
  Cpu,
  GraduationCap,
  Stethoscope,
  Mic,
  Briefcase,
  Library,
  CircuitBoard,
  Flower2,
  Network,
  Clapperboard,
  Cog,
  Code2,
  FileCode,
  HeartPulse,
  Hammer,
  BookOpenCheck,
  Award,
  Users,
  Wrench,
  CalendarClock,
  Wallet,
  BadgeCheck,
  BookOpen,
  TrendingUp,
  ThumbsUp,
  Trophy,
  HeartHandshake,
};

/** Render a registered lucide icon by name (for data-driven icons). */
export default function Icon({ name, ...props }) {
  const LucideIcon = registry[name] || Circle;
  return <LucideIcon {...props} />;
}
